---
- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Install packages
  apt:
    name:
      - apt-transport-https
      - gnupg2
      - software-properties-common
    state: present
    update_cache: yes

- name: Add apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Install packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Ensure docker service is enabled
  systemd:
    name: docker
    state: started
    enabled: yes
